# Generated by Django 3.0.2 on 2020-01-19 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', models.TimeField()),
                ('price', models.FloatField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=250)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('create_joining_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True)),
                ('payment_type', models.CharField(blank=True, max_length=250)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makingapp.Appointments')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('mobile', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=50)),
                ('appointment_time', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(null=True)),
                ('create_time', models.TimeField()),
                ('state_location', models.CharField(blank=True, max_length=250)),
                ('city_location', models.CharField(blank=True, max_length=250)),
                ('area_location', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makingapp.Categories')),
            ],
        ),
        migrations.AddField(
            model_name='appointments',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makingapp.Categories'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makingapp.Customers'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makingapp.Employees'),
        ),
    ]
